name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: Describe your idea.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: "Other approaches you've considered."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
