name: Question
description: Ask a question or get help
labels: ["question"]
type: Question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish?
